### ISSUE TITLE
About accuracy in paper.

### ISSUE THREAD

**Issue by HenryZ94264** [kminsoo/AFC#1]
Hello, excellent work!
I have noticed the _average incremental accuracy_ reported in the paper is following iCaRL, is it the top-5 accuracy? And the rest accuracies in the paper are the same evaluation(top-5)?
Thank you and have a nice day!

**Comment by kminsoo** [comment]
Hello. 
Thank you for your interest about AFC.
The average incremental accuracy is top-1 accuracy not top-5 accuracy. 
Have a nice day!

**Comment by HenryZ94264** [comment]
That is an amazing improvement!
Thank you!
