### ISSUE TITLE
Question on your paper !

### ISSUE THREAD

**Issue by sgmath12** [kminsoo/AFC#3]
Hello,

In equation (6) and (7), paper derives upper bound to avoid storing feature maps or performing back-propagation procedure, leading to equation (10).

However, in equation (10) there is still feature map Z and Z' and gradients. 
I think I miss something on your paper, If you can help me, it really help to me.
Thanks.

**Comment by sgmath12** [comment]
I got it

in euqation (10) it just needs gradient norm according to channels so it is marginal.
So it does not need to store whole gradient on feature maps!

**Comment by kminsoo** [comment]
Hello. 
Thank you for your interest about AFC. 
As you mentioned, the additional cost to store the importance for each channel can be marginal.
