### ISSUE TITLE
About the importance

### ISSUE THREAD

**Issue by windbro98** [kminsoo/AFC#6]
Hello, sir.
In the Analysis and Ablation Studies section of your paper, I'm quite interested in the comarision with feature distillation approaches. You show that Uniform Importance (setting all importance to 1) 's accuracy is 42.21, which is much lower than afc (62.58).  
In my experiment, I've set `feature_distil_factor` in the afc model to None, to set the importance to 1. However, the final incremental accuracy is about the same with the original afc. 
I'd like to know if it is due to my wrong operation. If so, how should I fork the Uniform Importance experiment.
Thank you.

**Comment by kminsoo** [comment]
Thank you for your interests about AFC.
The uniform importance results are obtained from Table 6 of [PODNet main paper] (https://arxiv.org/pdf/2004.13513.pdf). (Please refer to the POD-pixels row in Table 6.)
To reproduce the experiment, please refer to https://github.com/arthurdouillard/incremental_learning.pytorch/blob/master/options/podnet/ablations/perceptual_losses/podnet_cnn_podFlat_podPixels_cifar100.yaml
In the yaml file, you should delete the pod-flat loss.

Thank you!

**Comment by windbro98** [comment]
Thank you, sir.
